apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
  namespace: crochunter-dev
data:
  sha: "{{ .Values.commit.sha }}"
  branch: "{{ .Values.commit.branch }}"
  repo: "{{ .Values.commit.repo }}"