# Default values for croc-hunter.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

service:
  type: ClusterIP
servicePort: 80
containerPort: 8080
component: "croc-hunter"
replicas: 3
image: rackacr2.azurecr.io/villanub/croc-hunter
imageTag: master
imagePullPolicy: Always
## If you have a private registry you specify a secret to use --- add note about how secrets work with jenkinsfile set// 
imagePullSecrets: 
  name: "vsts-secret"
cpu: "10m"
memory: "128Mi"
## Ingress settings
ingress:
  enabled: true
  hostname: crochunter.rackerazr.com
  annotations:
     kubernetes.io/ingress.class: nginx
     certmanager.k8s.io/cluster-issuer: letsencrypt-prod
     kubernetes.io/tls-acme: "true"
  tls: true
## PodDisruptionBudget
pdb:
  enabled: false
  minAvailable: 2
## Config Map
commit:
  sha: "8c149d9"
  branch: "master"
  repo : "jldeen/crochunter"
