# Default values for croc-hunter.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

service:
  type: ClusterIP
servicePort: 80
containerPort: 8080
component: "croc-hunter"
replicas: 3
image: "quay.io/lachie83/croc-hunter"
imageTag: "latest"
imagePullPolicy: Always
cpu: "10m"
memory: "128Mi"
## Ingress settings
ingress:
  enabled: true
  hostname: ben-akscluster.eastus.cloudapp.azure.com
  annotations:
     kubernetes.io/ingress.class: nginx
     certmanager.k8s.io/cluster-issuer: letsencrypt-staging
     kubernetes.io/tls-acme: "true"
  tls: true
## PodDisruptionBudget
pdb:
  enabled: false
  minAvailable: 2

