--- 
component: croc-hunter
containerPort: 8080
cpu: 10m
image: rackacr2.azurecr.io/villanub/croc-hunter
imagePullPolicy: Always
imageTag: latest
imagePullSecrets:
  name: acr-auth
ingress: 
  annotations: 
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  enabled: true
  hostname: ben-akscluster.eastus.cloudapp.azure.com
  tls: true
memory: 128Mi
pdb: 
  enabled: false
  minAvailable: 2
replicas: 3
service: 
  type: ClusterIP
servicePort: 80