--- 
component: croc-hunter
containerPort: 8080
cpu: 10m
image: quay.io/lachie83/croc-hunter
imagePullPolicy: Always
imagePullSecrets: 
  name: acr-auth
imageTag: latest
ingress: 
  annotations: 
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  enabled: true
  hostname: ben-akscluster.eastus.cloudapp.azure.com
  tls: true
memory: 128Mi
pdb: 
  enabled: false
  minAvailable: 2
replicas: 3
service: 
  type: ClusterIP
servicePort: 80